services:
  www:
    container_name: hr-talent-www
    build:
      dockerfile: Dockerfile.local
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
    ports:
      - '4201:4201'
    networks:
      - hr-talent-network
networks:
  hr-talent-network:
